version: '3.8'

services:
  vitalid-backend:
    build: .
    container_name: vitalid-backend
    environment:
      SPRING_DATASOURCE_URL: 
      SPRING_DATASOURCE_USERNAME: vitalid_user
      SPRING_DATASOURCE_PASSWORD: vitalid_password
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: unless-stopped
